---
title: "backcalc Means Test Cases"
output: rmarkdown::html_vignette
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

```{r, include=FALSE}
if (!require(backcalc)) {
  if (!require(remotes)) install.packages("remotes")
  remotes::install_github("cwendorf/backcalc")
}
library(backcalc)
```

## Published One Sample Cases

```{r}
# Loftus & Palmer (1974) — "Smashed" Condition
backcalc_means(m = 40.8, se = 1.19, df = 44)

# Dutton & Aron (1974) — High Bridge Condition
backcalc_means(m = 2.99, se = 0.268, df = 19)
```

## Published Paired Sample Cases

```{r}
# Milgram (1963) — Shock Differences
backcalc_means(m = 0.15, se = 0.05, df = 39, paired = TRUE)

# Stanford Prison — Aggression Scores
backcalc_means(m = 2.0, se = 0.306, df = 23, paired = TRUE)
```

## Published Two Sample Cases

```{r}
# Bandura et al. (1961) — Bobo Doll Study
backcalc_means(m = 1.0, se = 0.217, df = 45)

# Asch (1951) — Conformity Rates
backcalc_means(m = 0.32, se = 0.0259, df = 58)
```
